# Generated by Django 3.0.7 on 2020-07-27 17:21

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('vote_counter', models.SmallIntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TagListModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('vote_counter', models.SmallIntegerField(default=0)),
                ('approved', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='QA.QuestionModel')),
            ],
            options={
                'unique_together': {('author', 'question')},
            },
        ),
        migrations.CreateModel(
            name='QVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_or_dislike', models.CharField(choices=[('like', 'like'), ('none', 'none'), ('dislike', 'dislike')], default='none', max_length=7)),
                ('question_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QA.QuestionModel')),
                ('user_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_key', 'question_key')},
            },
        ),
        migrations.CreateModel(
            name='QTagModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QA.QuestionModel')),
                ('tag_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QA.TagListModel')),
            ],
            options={
                'unique_together': {('tag_key', 'question_key')},
            },
        ),
        migrations.CreateModel(
            name='AVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_or_dislike', models.CharField(choices=[('like', 'like'), ('none', 'none'), ('dislike', 'dislike')], default='none', max_length=7)),
                ('answer_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QA.AnswerModel')),
                ('user_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_key', 'answer_key')},
            },
        ),
    ]
