# Generated by Django 3.0.7 on 2020-07-30 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qtagmodel',
            old_name='question_key',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='qtagmodel',
            old_name='tag_key',
            new_name='tag',
        ),
        migrations.AlterUniqueTogether(
            name='qtagmodel',
            unique_together={('tag', 'question')},
        ),
    ]
