# Generated by Django 3.0.7 on 2020-08-08 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0002_auto_20200808_0636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answermodel',
            name='approved',
        ),
        migrations.CreateModel(
            name='AnswerApproved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QA.AnswerModel')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QA.QuestionModel')),
            ],
            options={
                'unique_together': {('answer', 'question')},
            },
        ),
    ]
