# Generated by Django 3.0.7 on 2020-08-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0004_auto_20200809_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='answermodel',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
