# Generated by Django 3.0.7 on 2020-08-11 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0005_answermodel_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerapproved',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QA.QuestionModel', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='answerapproved',
            unique_together=set(),
        ),
    ]
