# Generated by Django 3.0.7 on 2020-08-11 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0006_auto_20200811_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerapproved',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='QA.QuestionModel'),
        ),
    ]
