# Generated by Django 3.0.7 on 2020-08-11 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0007_auto_20200811_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerapproved',
            name='id',
        ),
        migrations.AlterField(
            model_name='answerapproved',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='QA.QuestionModel'),
        ),
    ]
