# Generated by Django 3.0.7 on 2020-08-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0009_auto_20200811_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmodel',
            name='review',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
