# Generated by Django 3.0.7 on 2020-08-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0010_questionmodel_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answermodel',
            old_name='vote_counter',
            new_name='vote',
        ),
        migrations.RenameField(
            model_name='questionmodel',
            old_name='vote_counter',
            new_name='vote',
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='answers_No',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
