# Generated by Django 3.0.7 on 2020-08-27 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0011_auto_20200827_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionmodel',
            old_name='answers_No',
            new_name='answers_NO',
        ),
    ]
