# Generated by Django 2.2.7 on 2020-09-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0012_auto_20200827_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='answermodel',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
