# Generated by Django 2.2.7 on 2020-09-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0014_answermodel_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='avote',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='avote',
            constraint=models.UniqueConstraint(fields=('answer', 'user'), name='avote'),
        ),
    ]
