# Generated by Django 3.1.1 on 2020-09-13 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0017_auto_20200913_1813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionmodel',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='answermodel',
            old_name='date_at',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='questionmodel',
            old_name='date_at',
            new_name='date',
        ),
    ]
