# Generated by Django 2.2.7 on 2020-09-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'ordering': ['-reputation']},
        ),
        migrations.AddField(
            model_name='usermodel',
            name='answers_no',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='questions_no',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
