# Generated by Django 2.2.7 on 2020-09-18 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200917_0834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='last_seen',
            new_name='last_visit',
        ),
    ]
