# Generated by Django 2.2.7 on 2020-09-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usermodel_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='join_date',
            field=models.DateField(),
        ),
    ]
