# Generated by Django 2.2.7 on 2020-09-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200913_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='join_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
